### ISSUE TITLE
Relevant updates might be delayed for all users by poorly timed request

### ISSUE THREAD

**Issue by Yarb** [binuixman/amparibot#1]
Because of the rate limiting approach used in the code a poorly timed query by any user can cause a significant delay in relevant updates.
Most updates to storefront offerings usually happen on the hour (18:00, 20:00 and so on) and these are probably updated to the Cheapshark few minutes later. If a user does a request few minutes before the storefront update, no new request can be made by any user until rate limit timeout of 3600 seconds has passed. Thus users can (un)intentionally delay these updates on new games.

**Example:**
User A wants to see new updates on the Epic storefront offerings which are released at 18:00. Thus he makes a request at 18:01 according to his clock. Unfortunately there is a slight clock skew and the actual time of this request is 17:59.
Request is made by the bot and the new results are posted to user. Unfortunately the new free games are missing as the storefront hasn't updated them yet.

User B makes a request 18:10 to see the same Epic storefront updates. He will get the same result as user A as it has been 10 or so minutes since last request. User B now needs to wait till 18:59 to do a request and get a listing of new free games from Epic storefront.
Both users might have a bad experience as neither probably knows about the 1 hour rate limit.

**Possible solutions:**
- Allow an additional request some time after the hour has changed
- Do additional requests on set times of the day. 18:10 for instance.
- Adjust the rate limits or make them progressive.
- Notify users on the last query time and/or when the next update is possible.
    - Possibly allow users to force an additional request.

**Comment by binuixman** [comment]
Default interval for queries set to 300 seconds (5 minutes). This is easily adjustable by changing _interval_ variable on _bot_startup.py_. Closing the issue for now.

**Comment by binuixman** [comment]
Issue closed.
